# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:12.14-alpine

before_script:
  - yarn install

stages:
  - build

.default-rule: &default-rule
  if: '$CI_MERGE_REQUEST_IID || $CI_COMMIT_REF_SLUG == "master"'

.be-package:
  variables:
    PACKAGE: "backend"
  before_script:
    - cd backend
  only:
    changes:
      - "backend/**/*"

.fe-package:
  variables:
    PACKAGE: "frontend"
  before_script:
    - cd frontend
  only:
    changes:
      - "frontend/**/*"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist/

.build-package:
  stage: build
  script:
    - echo "Building $PACKAGE"
    - yarn build
  rules:
    - <<: *default-rule

build-be-package:
  extends:
    - .build-package
    - .be-package

build-fe-package:
  extends:
    - .build-package
    - .fe-package

